/* ===================================================================
   Lesson video IDs — SERVER SIDE ONLY.

   The "_" prefix means Vercel does not route this file, so it is never
   served to a browser. That is the point: if the YouTube ids shipped in
   the page source, anyone could read them from devtools and watch every
   paid lesson for free, and the paywall would be decoration.

   /api/lesson-video hands out a URL only after checking the caller's
   access token (or that the lesson is a free preview).

   Generated by lesson-video/scripts/sync-course-videos.mjs — run that
   after uploading to YouTube rather than editing this by hand.
   =================================================================== */

const LESSON_VIDEOS = {
  'ai-basics': {
    // 'ab-01': 'YOUTUBE_VIDEO_ID',
  },
};

/* Unlisted YouTube videos are embeddable, which is what makes this work
   without hosting the files ourselves. */
function embedUrlFor(courseId, lessonId) {
  const course = LESSON_VIDEOS[courseId];
  if (!course) return null;
  const id = course[lessonId];
  if (!id) return null;
  return 'https://www.youtube-nocookie.com/embed/' + id;
}

module.exports = { LESSON_VIDEOS, embedUrlFor };
