/* ===================================================================
   Lesson video IDs — SERVER SIDE ONLY.

   The "_" prefix means Vercel does not route this file, so it is never
   served to a browser. That is the point: if the YouTube ids shipped in
   the page source, anyone could read them from devtools and watch every
   paid lesson for free, and the paywall would be decoration.

   /api/lesson-video hands out a URL only after checking the caller's
   access token (or that the lesson is a free preview).

   Generated by lesson-video/scripts/sync-course-videos.mjs — run that
   after uploading to YouTube rather than editing this by hand.
   =================================================================== */

const LESSON_VIDEOS = {
  'prompt-eng': {
    'pe-01': 'vyjAi84ZtIw',
    'pe-02': 'RQJGe2pUVFw',
    'pe-03': 'azLCsyTrw2k',
    'pe-04': 'Fafi8j13ugs',
    'pe-05': 'rlG755O0FKs',
    'pe-06': 'a8vth05t20Q',
    'pe-07': 'BG-FA17-rq8',
    'pe-08': '6hBL6Frhd0A',
    'pe-09': 'C-A1nieH02I',
    'pe-10': 'A7VWScb9uxI',
    'pe-11': 'r-WlDksNxuk',
  },
  'ai-basics': {
    'ab-01': 'DxObASOUfHM',
    'ab-02': '14XZgfRzfKA',
    'ab-03': '7QbnN5eTYQk',
    'ab-04': 'X-QjcI2uV6w',
    'ab-05': 'uXL6QGqekPw',
    'ab-06': 'aM9jJZ6Qm-g',
    'ab-07': '6CTbEmeGYNs',
    'ab-08': 'HgS0p0IEh0w',
    'ab-09': 'GRKNYSIYQcE',
    'ab-10': 'P-QnvPMK0tY',
  },
};

/* Unlisted YouTube videos are embeddable, which is what makes this work
   without hosting the files ourselves. */
function embedUrlFor(courseId, lessonId) {
  const course = LESSON_VIDEOS[courseId];
  if (!course) return null;
  const id = course[lessonId];
  if (!id) return null;
  return 'https://www.youtube-nocookie.com/embed/' + id;
}

module.exports = { LESSON_VIDEOS, embedUrlFor };
